# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Texto',
        ),
    ]
